<?php
require_once './phps/connect.php';
$_SESSION['page'] = 'explore';
require_once './header.php';
?>

<style>
    .card{transition:.5s;background-color:#d67c55!important;border-radius:25px!important}.card-img-top{border-radius:25px 25px 0 0!important}.card:hover{transition:.5s;transform:scale(1.1)}.card-text{color:#fff}body{background-image:url(assets/background/cv.png);background-color:#c55d50}.carousel-control-next-icon,.carousel-control-prev-icon{height:100px;width:100px;background-size:50%,50%}.carousel-inner>.item{position:relative;display:none;-webkit-transition:10ms ease-in-out left;-moz-transition:10ms ease-in-out left;-o-transition:10ms ease-in-out left;transition:10ms ease-in-out left}::-webkit-scrollbar{width:8px;border-radius:10px}::-webkit-scrollbar-track{background:#c55d50}::-webkit-scrollbar-thumb{background:#fdcd5f;background-clip:padding-box}.dept-logo{width:60px;padding:1px}.sorry{position:absolute;top:50%;left:50%;transform:translate(-50%,-50%)}@media screen and (max-width:768px){body{background-image:none;background-color:#c55d50}.sorry{position:static;top:0;left:0;transform:none;display:grid;place-items:center;margin-top:5%;padding:0 20px}}.btn-red{border-radius:40px!important;background-color:#dc3545!important;color:#fff!important;transition:.3s!important}.btn-red:hover{transition:.3s;color:#fdcd5f}.btn{transition:.3s;background-color:#fdcd5f;border:none;border-radius:25px;color:#000;-webkit-appearance:none;font-weight:700}.btn:hover{transition:.3s;background:#7c6ed1;color:#fff}
</style>

<style>
    .container {
    
    }
    @media screen and (max-width: 768px) {
        .container {
            margin-left: 2px;
        }
    }
</style>

<?php
if ($rowMahasiswa['status'] != 0) {
?>
    <style type="text/css">
        @keyframes ldio-7xufn7u97p6{0%{transform:rotate(0)}100%{transform:rotate(360deg)}}.ldio-7xufn7u97p6>div>div{transform-origin:100px 100px;animation:ldio-7xufn7u97p6 3.0303030303030303s linear infinite;opacity:.8}.ldio-7xufn7u97p6>div>div>div{position:absolute;left:30px;top:30px;width:70px;height:70px;border-radius:70px 0 0 0;transform-origin:100px 100px}.ldio-7xufn7u97p6>div div:nth-child(1){animation-duration:.7575757575757576s}.ldio-7xufn7u97p6>div div:nth-child(1)>div{background:#e15b64;transform:rotate(0)}.ldio-7xufn7u97p6>div div:nth-child(2){animation-duration:1.0101010101010102s}.ldio-7xufn7u97p6>div div:nth-child(2)>div{background:#f47e60;transform:rotate(0)}.ldio-7xufn7u97p6>div div:nth-child(3){animation-duration:1.5151515151515151s}.ldio-7xufn7u97p6>div div:nth-child(3)>div{background:#f8b26a;transform:rotate(0)}.ldio-7xufn7u97p6>div div:nth-child(4){animation-duration:3.0303030303030303s}.ldio-7xufn7u97p6>div div:nth-child(4)>div{background:#abbd81;transform:rotate(0)}.loadingio-spinner-wedges-n24ir3anbsf{width:200px;height:200px;display:inline-block;overflow:hidden}.ldio-7xufn7u97p6{width:100%;height:100%;position:relative;transform:translateZ(0) scale(1);backface-visibility:hidden;transform-origin:0 0}.ldio-7xufn7u97p6 div{box-sizing:content-box}.jconfirm-content{max-height:50vh;padding:15px;}.jconfirm.jconfirm-modern .jconfirm-box div.jconfirm-title-c{padding-bottom:0!important;}
        /* generated by https://loading.io/ */
    </style>
<?php
}
?>

<body>
    <div class="container">
        <?php
        if ($rowMahasiswa['status'] == 0) {
        ?>
            <div class="sorry justify-content-center">
                <h1 style="text-align: center; letter-spacing: 5px; color: #FDCD5F;font-weight: 500;">MOHON MAAF</h1>
                <h5 style="text-align: center; color: white;" class="mt-3">Silakan mengisi Curriculum Vitae (CV) di halaman <a href="profile.php" style="text-decoration: none; color: #FDCD5F; font-weight: bold;">Profile</a> terlebih dahulu untuk dapat mengakses halaman ini.</h5>
                <h5 style="text-align: center; color: white;" class="mt-3">Melalui halaman <span style="text-decoration: none; color: #FDCD5F; font-weight: bold;">Explore</span>, kamu dapat melihat lebih dari <span style="text-decoration: none; color: #FDCD5F; font-weight: bold;"><?= intval(getPetranesiansHitzCount() / 10) * 10 ?></span> profil Petranesians lain yang sudah terhubung di <span style="color: #FDCD5F; font-weight: bold;">R E A C H</span>, lho. Jadi, tunggu apalagi? Yuk, segera isi CV-mu di halaman <a href="profile.php" style="text-decoration: none; color: #FDCD5F; font-weight: bold;">Profile</a> yah, Petranesian! &#128588;</h5>
                <center class="row my-5 justify-content-center">
                    <img class="dept-logo" src="./assets/image/HRD.png" alt="HRD">
                    <img class="dept-logo" src="./assets/image/IS.png" alt="IS">
                    <img class="dept-logo" src="./assets/image/SNC.png" alt="SNC">
                </center>
            </div>
        <?php
        } else {
        ?>
            <div data-aos="fade-up">
                <div class="title-row mx-2">
                    <h2 class="title" style="color: #FDCD5F; letter-spacing: 5px;">Explore Petranesians</h2>
                    <h6 class="title" style="color: #FDCD5F; letter-spacing: 5px;">click on Petranesian to see the profile!</h6>
                </div>
                <div class="row justify-content-center">
                    <div class="col-12 col-md-5 mt-3">
                        <select class="form-control" id="filter_divisi" name="filter_divisi" style="height:40px; font-size: 12pt; background-color:#D67C55;color:white; border-radius:25px!important;border:none;" onchange="toggleFilter()">
                            <option value="">Cari berdasarkan divisi...</option>
                            <option value="Acara">Acara</option>
                            <option value="PDD">PDD</option>
                            <option value="Sekretariat">Sekretariat</option>
                            <option value="Public Relation">Public Relation</option>
                            <option value="Perlengkapan">Perlengkapan</option>
                            <option value="Konsumsi">Konsumsi</option>
                            <option value="IT">IT</option>
                            <option value="Sponsor">Sponsor</option>
                            <option value="Keamanan">Keamanan</option>
                            <option value="Kesehatan">Kesehatan</option>
                            <option value="Materi">Materi</option>
                            <option value="Peran">Peran</option>
                            <option value="Asisten Tutor">Asisten Tutor</option>
                        </select>
                    </div>
                    <div class="col-12 col-md-5 mt-3">
                        <select class="form-control" id="filter_angkatan" name="filter_angkatan" style="height:40px; font-size: 12pt; background-color:#D67C55;color:white; border-radius:25px!important;border:none;" onchange="toggleFilter()">
                            <option value="">Lihat berdasarkan angkatan...</option>
                            <?php getBatchList() ?>
                        </select>
                    </div>
                </div>
                <div class="row justify-content-center">
                    <div class="col-12 col-md-5 mt-3">
                        <select class="form-control" id="filter_fakultas" name="filter_fakultas" style="height:40px; font-size: 12pt; background-color:#D67C55;color:white; border-radius:25px!important;border:none;" onchange="toggleFilter()">
                            <option value="">Lihat berdasarkan fakultas...</option>
                            <?php getFacultyList() ?>
                        </select>
                    </div>
                    <div class="col-12 col-md-5 mt-3">
                        <select class="form-control" id="filter_jurusan" name="filter_jurusan" style="height:40px; font-size: 12pt; background-color:#D67C55;color:white; border-radius:25px!important;border:none;" onchange="toggleFilter()">
                            <option value="">Lihat berdasarkan program studi...</option>
                            <?php getMajorList() ?>
                        </select>
                    </div>
                </div>
                <div class="row mx-2 justify-content-center mt-3 mb-2">
                    <center><a onclick="toggleFilter(true)" class="btn btn-danger mt-1" style='width: 150px;' id="reset_filter_button" hidden>Reset Filter</a></center>
                </div>
                <div class="row justify-content-center">
                    <p class="mt-3" style="color: #FDCD5F; font-size: 12pt;" id="not-found" hidden>Belum Ada Data</p>
                </div>

                <div class="container">
    <div class="row" id="gridContainer">
        <!-- Grid content will be inserted here -->
    </div>
</div>

                <div class="row mx-2 justify-content-center mb-2">
                    <center><a onclick="disclaimer()" class="btn btn-danger mt-1" style='width: 200px;'>Disclaimer</a></center>
                </div>
                <div class="row mx-2 justify-content-center mb-5">
                    <center><a onclick="mitosAtauFakta()" class="btn btn-danger mt-1" style='width: 200px;'>Mitos atau Fakta?</a></center>
                </div>
            </div>
        <?php
        }
        ?>
    </div>

    <script>
        <?php
        if ($rowMahasiswa['status'] != 0) {
            if (checkThisWeeksBirthday()) {
        ?>
                $.confirm({
                    title: '<span style="color: #3C6CB4;">Happy Birthday!</span>',
                    theme: "modern",
                    columnClass: "col-12 col-md-5",
                    containerFluid: !0,
                    typeAnimated: !0,
                    draggable: false,
                    buttons: {
                        cancel: {
                            text: "CLOSE",
                            btnClass: "red-so btn-red"
                        }
                    },
                    content: `<div style=\'color: #3C6CB4; font-size: 14pt;\'>This week\'s joyful Petranesians<br>🥳🎉<br><br><?php getThisWeeksBirthday(sanitizeString($rowMahasiswa['nama'])) ?>May God bless you all abundantly!<br><a href="https://youtu.be/K4Ei6x1ofCk" target="_blank"><img src="./assets/gif/birthday.gif" style="width: 200px"></a></div>`
                })
            <?php
            }
            ?>
            
            
            function displayPetranesians() {
    $("#gridContainer").html("<div class='loadingio-spinner-wedges-n24ir3anbsf'><div class='ldio-7xufn7u97p6'><div><div><div></div></div><div><div></div></div><div><div></div></div><div><div></div></div></div></div></div>");

    setTimeout(function () {
        $.ajax({
            url: "phps/refresh_data.php",
            type: "get",
            dataType: "json",
            data: { id: 8 },
            success: function (data) {
                var profilesHTML = "";

                for (var i = 0; i < data.length; i++) {
                    var profile = data[i];

                    profilesHTML += '<div class="col-md-4 mb-3">'; 

                    profilesHTML += '<div class="card mx-2 shadow bg-white rounded" style="width: 18rem;">';
                    profilesHTML += '<a href="view_profile.php?nrp=' + profile.nrp + '" target="_blank" style="text-decoration: none; color: black;">';
                    profilesHTML += '<img class="card-img-top" src="uploads/cv_photo/' + profile.photo_filepath + '" alt="' + profile.nama + '" style="max-height: 450px;">';

                    profilesHTML += '<div class="card-body">';
                    profilesHTML += '<h5 class="card-title" style="color: #FDCD5F;">' + profile.nama + '</h5>'; 
                    profilesHTML += '<p class="card-text">' + profile.fakultas + '</p>';
                    profilesHTML += '<p class="card-text">' + profile.program + '</p>';
                    profilesHTML += '<p class="card-text">' + profile.angkatan + '</p>';
                    profilesHTML += '</div></a></div></div>';
                }

                $("#gridContainer").html('<div class="container justify-content-center">' +
                                          '<div class="row">' + profilesHTML + '</div>' +
                                          '</div>'); 

            },
            error: function (a) {
                alert("Mohon maaf, terjadi error di server. Silakan coba ulangi kembali.");
            }
        });
    }, 1000);
}

            
            function mitosAtauFakta(){$.confirm({title:'<span style="color: #3C6CB4;">ril or feiki?</span>',theme:"modern",columnClass:"col-12 col-md-8",buttons:{cancel:{text:"CLOSE",btnClass:"btn-red"}},content:'\n                <center style="color: #3C6CB4; font-size: 14pt;"><img src="./assets/gif/confused.gif" style="width: 200px; cursor: pointer;" onclick="alert(\'Jangan-jangan kamu, yah? \u{1F914}\')"><br>Konon katanya ada <a style="text-decoration: none; font-weight: bold; cursor: pointer;" onclick="alert(\'Jangan-jangan kamu, yah? \u{1F914}\')">Mahasiswa/i</a> yang request halaman ini buat cari <b><strike>Petranesian Berkualitas</strike></b> jodoh, lho!\n                </center>\n            '})}
            
            function disclaimer(){$.confirm({title:'<span style="color: #3C6CB4;">Disclaimer</span>',theme:"modern",columnClass:"col-12 col-md-8",buttons:{cancel:{text:"CLOSE",btnClass:"btn-red"}},content:'\n                <center style="color: #3C6CB4; font-size: 14pt;">\n                    Data yang ditampilkan pada hasil pencarian divisi <b>tidak 100% akurat</b>. Sistem akan menampilkan profil Petranesians dengan urutan acak berdasarkan <b>kepanitiaan yang sudah pernah dilakukan input</b> oleh Departemen HRD BEM UK Petra pada <b>database REACH</b> dan berdasarkan <b>Pengalaman Organisasi dan Kepanitiaan</b> yang dilakukan input Petranesians pada halaman <a href="./profile.php" target="_blank" style="text-decoration: none; font-weight: bold; color: #3C6CB4">Profile</a>. Silakan menampilkan <b>salah satu kata kunci</b> di bawah ini pada kolom <b>Pengalaman Organisasi dan Kepanitiaan</b> untuk membantu Petranesians agar dapat ditampilkan sesuai divisi yang sudah pernah Petranesians ambil atau tertarik.<br><br>\n                    <span style="font-weight: bold; font-size: 16pt;">Kata Kunci</span><br>\n                    <b>Acara</b> \u2013 <i>acara, mc, master of ceremony</i><br>\n                    <b>PDD</b> \u2013 <i>pdd, publikasi, dekorasi, dekor,  dokumentasi, creative</i><br>\n                    <b>Sekretariat</b> \u2013 <i>sekretaris, sekretariat, sekret, sekkon, sekon, sekkonkes, sekonkes, gsab</i><br>\n                    <b>Public Relation</b> \u2013 <i>pr, public relation, humas, hubungan masyarakat</i><br>\n                    <b>Perlengkapan</b> \u2013 <i>perkapman, transkapman, transakap, perlengkapan, perkap, supply</i><br>\n                    <b>Konsumsi</b> \u2013 <i>konsumsi, konsum, sekkon, sekon, konkes</i><br>\n                    <b>IT</b> \u2013 <i>it, information, informasi, technology, teknologi, sistem, system, sistem informasi, teknologi informasi, information technology</i><br>\n                    <b>Sponsor</b> \u2013 <i>sponsor, sponsorship, dana, danus, dana usaha</i><br>\n                    <b>Keamanan</b> \u2013 <i>keamanan, transkaman, transkapman, perkapman</i><br>\n                    <b>Kesehatan</b> \u2013 <i>kesehatan, konkes, sekkonkes, sekonkes</i><br>\n                    <b>Materi</b> \u2013 <i>materi</i><br>\n                    <b>Peran</b> \u2013 <i>peran, frontline, front line, fl</i><br>\n                    <b>Asisten Tutor</b> \u2013 <i>asisten tutor, astor</i><br>\n                </center>\n            '})}function getAllMajor(){$.ajax({url:"phps/get_faculty_program.php",method:"POST",success:function(a){$("#filter_jurusan").html('<option value="">Lihat berdasarkan program studi...</option>'+a)},error:function(a){alert("Mohon maaf, terjadi error di server. Silakan coba ulangi kembali.")}})}function toggleFilter(a=!1){$("#filter_divisi").val()||$("#filter_angkatan").val()||$("#filter_fakultas").val()||$("#filter_jurusan").val()||$("#reset_filter_button").prop("hidden",!0),$("#not-found").prop("hidden",!0),$(".carousel").prop("hidden",!1),a&&($("#filter_divisi").val(""),$("#filter_angkatan").val(""),$("#filter_fakultas").val(""),$("#filter_jurusan").val(""),$("#reset_filter_button").prop("hidden",!0),getAllMajor()),""==$("#filter_divisi").val()&&""==$("#filter_angkatan").val()&&""==$("#filter_fakultas").val()&&""==$("#filter_jurusan").val()||$("#reset_filter_button").removeAttr("hidden"),$(".carousel-inner").html("<center><div class='loadingio-spinner-wedges-n24ir3anbsf'><div class='ldio-7xufn7u97p6'><div><div><div></div></div><div><div></div></div><div><div></div></div><div><div></div></div></div></div></div></center>"),setTimeout(function(){var c=$("#filter_divisi").val(),d=$("#filter_angkatan").val(),a=$("#filter_fakultas").val(),b=$("#filter_jurusan").val();""!=a&&""==b&&$.ajax({url:"phps/get_faculty_program.php",data:{fakultas:a},method:"POST",success:function(a){$("#filter_jurusan").html('<option value="">Lihat berdasarkan program studi...</option>'+a)},error:function(a){alert("Mohon maaf, terjadi error di server. Silakan coba ulangi kembali.")}}),$.ajax({url:"phps/refresh_data.php",type:"get",dataType:"json",data:{id:8,divisi:c,angkatan:d,fakultas:a,jurusan:b},success:function(e){var d=e;if(d.length>0){$("#not-found").prop("hidden",!0),$(".carousel").prop("hidden",!1);for(var c="",b=0;b<d.length;b++){var a=d[b];c+=0!=b?'\n                                <div class="carousel-item">\n                            ':'\n                                <div class="carousel-item active">\n                            ',c+='\n                            <center>\n                                <div class="card mx-2 shadow bg-white rounded" style="width: 18rem;">\n                                    <a href="view_profile.php?nrp='+a.nrp+'" target="_blank" style="text-decoration: none; color: black;">\n                        ',0==b||1==b||b==d.length-1?c+='\n                                        <img class="card-img-top" src="uploads/cv_photo/'+a.photo_filepath+'" alt="'+a.nama+'" style="max-height: 450px;">\n                            ':c+='\n                                        <img loading="lazy" class="card-img-top" src="uploads/cv_photo/'+a.photo_filepath+'" alt="'+a.nama+'" style="max-height: 450px;">\n                            ',c+='\n                                        <div class="card-body">\n                                            <div class="row justify-content-center mx-2">\n                                                <h5 style="font-weight: bold; color: #FDCD5F;">'+a.nama+'</h5>\n                                            </div>\n                                            <div class="row mt-2 justify-content-center">\n                                                <p class="card-text">'+a.fakultas+'</b></p>\n                                            </div>\n                                            <div class="row justify-content-center">\n                                                <p class="card-text">'+a.program+'</p>\n                                            </div>\n                                            <div class="row mt-2 justify-content-center">\n                                                <p class="card-text">'+a.angkatan+"</p>\n                                            </div>\n                                        </div>\n                                    </a>\n                                </div>\n                            </center>\n                        </div>\n                        "}$(".carousel-inner").html(c)}else $(".carousel").prop("hidden",!0),$("#not-found").prop("hidden",!1)},error:function(a){alert("Mohon maaf, terjadi error di server. Silakan coba ulangi kembali.")}})},1e3)}$("#filter_fakultas").on("change",function(){$("#filter_jurusan").val(""),getAllMajor()}),$(".carousel").bind("slide.bs.carousel",function(e){var a=$(".active.carousel-item",this).prev(".carousel-item").prev(".carousel-item"),b=$(".active.carousel-item",this).prev(".carousel-item").prev(".carousel-item").prev(".carousel-item");prevImage1=a.find("img").removeAttr("loading"),prevImage2=b.find("img").removeAttr("loading");var c=$(".active.carousel-item",this).next(".carousel-item").next(".carousel-item"),d=$(".active.carousel-item",this).next(".carousel-item").next(".carousel-item").next(".carousel-item");nextImage1=c.find("img").removeAttr("loading"),nextImage2=d.find("img").removeAttr("loading")}),$(document).ready(function(){displayPetranesians()});var tooltipTriggerList=[].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]')),tooltipList=tooltipTriggerList.map(function(a){return new bootstrap.Tooltip(a)})
        <?php
        }
        ?>
    </script>
    <script src="https://unpkg.com/aos@next/dist/aos.js"></script>
    <script>
        AOS.init();
    </script>
</body>

</html>